export const MOCK_BOOKS = [
  {
    id: "1",
    title: "Clean Code",
    author: "Robert C. Martin",
    isbn: "9780132350884",
    categories: ["Technology"],
    totalCopies: 5,
    availableCopies: 2,
    coverImage: "/clean-code-book-cover.png",
    description: "A handbook of agile software craftsmanship, focusing on writing readable, maintainable code.",
  },
  {
    id: "2",
    title: "The Pragmatic Programmer",
    author: "Andrew Hunt, David Thomas",
    isbn: "9780201616224",
    categories: ["Technology"],
    totalCopies: 4,
    availableCopies: 0,
    coverImage: "/the-pragmatic-programmer-book-cover.jpg",
    description: "Timeless tips and techniques for effective software development and career growth.",
  },
  {
    id: "3",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    isbn: "9780062316097",
    categories: ["History", "Science"],
    totalCopies: 6,
    availableCopies: 4,
    coverImage: "/sapiens-book-cover.png",
    description: "Explores the history and impact of Homo sapiens on the world, from ancient times to the present.",
  },
  {
    id: "4",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    isbn: "9780061120084",
    categories: ["Fiction"],
    totalCopies: 7,
    availableCopies: 1,
    coverImage: "/to-kill-a-mockingbird-cover.png",
    description: "A classic novel addressing racial injustice and moral growth in the American South.",
  },
  {
    id: "5",
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    isbn: "9780374533557",
    categories: ["Science", "Non-fiction"],
    totalCopies: 5,
    availableCopies: 3,
    coverImage: "/thinking-fast-and-slow-cover.png",
    description:
      "An exploration of the two systems that drive the way we think: fast, intuitive, and slow, deliberate.",
  },
  {
    id: "6",
    title: "Atomic Habits",
    author: "James Clear",
    isbn: "9780735211292",
    categories: ["Non-fiction"],
    totalCopies: 8,
    availableCopies: 5,
    coverImage: "/atomic-habits-cover.png",
    description: "A guide to building good habits and breaking bad ones through small, incremental changes.",
  },
]
